services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: v2
    volumes:
      - db_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["/rest"]
    depends_on:
      - mysql
      
  events:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    command: ["/events"]
    depends_on:
      - mysql
  notifications:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    command: ["/notifications"]
    depends_on:
      - mysql

  players:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    command: ["/players"]
    depends_on:
      - mysql

volumes:
  db_data: